### ISSUE TITLE
Design todo

### ISSUE THREAD

**Issue by MathieuUrstein** [Flagoul/swapp#41]
- [x] trashes under the inventory
- [x] advanced search with map
- [x] creation and edition of items
- [x] creation and edition of users
