### ISSUE TITLE
TODO design

### ISSUE THREAD

**Issue by MathieuUrstein** [Flagoul/swapp#70]
- [x] Visuel proposition (émission)
- [x] Visuel proposition (réception) échange
- [x] Visuel notifs
- [x] Visuel profil public
- [x] Recherche collée top
- [x] Binder la modal à tous les boutons profils (comme ajouter item)
